image: node:latest

stages:
  - build
  - test
  - code_quality
  - code_format
  - coverage_check
  - email_notification

variables:
  MAIL_TO: "anilchukkala1994@gmail.com"

before_script:
  - npm install

build:
  stage: build
  script:
    - npm run build

test:
  stage: test
  script:
    - npm test

code_quality:
  stage: code_quality
  script:
    - npm run lint

code_format:
  stage: code_format
  script:
    - npm run format:check

coverage_check:
  stage: coverage_check
  script:
    - npm run coverage:check

email_notification:
  stage: email_notification
  script:
    - echo "Sending notification email..."
  only:
    - master
  except:
    - email_notification
  when: on_failure  #
  after_script:
    - echo "Job finished"
    - if [[ "$CI_PIPELINE_SOURCE" == "push" ]]; then
        echo "Sending email notification...";
        echo "Pipeline failed! Check details here: $CI_PIPELINE_URL" | mail -s "Pipeline Failed" $MAIL_TO;
      fi
